# -*- coding: UTF-8 -*-

MODULAR_GRID_URL = 'https://www.modulargrid.net/e/modules/browser'

TERMINAL_WIDTH = 100

INVALID_BRAND_NAMES = [
    "ad infinitum",
    "alyseum",
    "birdkids",
    "buchla",
    "coming soon",
    u"e-rm erfindungsb\xfcro",
    "frap tools",
    "future retro",
    "grendel",
    "hackme electronics",
    "haken audio",
    "knas",
    "l.e.p",
    "l.e.p.",
    "manikin",
    "manufacturer",
    "meeblip",
    "modular",
    "moogmusic",
    "moon modular",
    "midisolutions",
    "niio analog",
    "other/unknown",
    "other manufacturers",
    "pedals",
    "plankton electronics",
    "ploytec gmbh",
    "reon",
    "sequentix",
    "sherman",
    "sitemap",
    "space case ltd",
    "special offers",
    "snd",
    "synths",
    "teenage engineering",
    "t-shirts",
    "tom oberheim",
    "used",
    "\n",
    "",
]
